<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    use HasFactory;

    public function delete()
    {
        $reports = QuestionError::where('question_id', $this->id)->get();

        foreach ($reports as $report) {
            $report->delete();
        }

        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
